const express = require('express');
const { requireRole } = require('../middleware/auth');
const { runClpctl, randomPassword, assertSafeArgValue, isValidDomain, deriveSiteUser, assertNotReservedUsername } = require('../lib/clpctl');
const audit = require('../lib/audit');

const router = express.Router();

const SITE_TYPES = ['nodejs', 'static', 'php', 'python', 'reverse-proxy'];

function buildArgs(body) {
  const { domainName, type, siteUser, siteUserPassword } = body;
  if (!isValidDomain(domainName)) throw new Error('Invalid domain name');
  if (!SITE_TYPES.includes(type)) throw new Error(`type must be one of: ${SITE_TYPES.join(', ')}`);

  const user = assertSafeArgValue('siteUser', siteUser || deriveSiteUser(domainName));
  assertNotReservedUsername(user);
  const password = siteUserPassword; // always server-generated by the caller

  const args = [`site:add:${type}`, `--domainName=${assertSafeArgValue('domainName', domainName)}`];

  if (type === 'nodejs') {
    const nodejsVersion = assertSafeArgValue('nodejsVersion', body.nodejsVersion || '22');
    const appPort = assertSafeArgValue('appPort', body.appPort);
    if (!/^\d+$/.test(appPort) || Number(appPort) < 1 || Number(appPort) > 65535) throw new Error('appPort must be a valid port number');
    args.push(`--nodejsVersion=${nodejsVersion}`, `--appPort=${appPort}`);
  } else if (type === 'php') {
    args.push(`--phpVersion=${assertSafeArgValue('phpVersion', body.phpVersion || '8.3')}`);
    args.push(`--vhostTemplate=${assertSafeArgValue('vhostTemplate', body.vhostTemplate || 'Generic')}`);
  } else if (type === 'python') {
    const pythonVersion = assertSafeArgValue('pythonVersion', body.pythonVersion || '3.12');
    const appPort = assertSafeArgValue('appPort', body.appPort);
    if (!/^\d+$/.test(appPort) || Number(appPort) < 1 || Number(appPort) > 65535) throw new Error('appPort must be a valid port number');
    args.push(`--pythonVersion=${pythonVersion}`, `--appPort=${appPort}`);
  } else if (type === 'reverse-proxy') {
    const url = assertSafeArgValue('reverseProxyUrl', body.reverseProxyUrl);
    if (!/^https?:\/\//i.test(url)) throw new Error('reverseProxyUrl must start with http:// or https://');
    args.push(`--reverseProxyUrl=${url}`);
  }
  // 'static' needs nothing beyond domainName

  args.push(`--siteUser=${user}`, `--siteUserPassword=${password}`);
  return { args, user };
}

// POST /api/vhosts — admin only, creates a new CloudPanel site via clpctl
router.post('/', requireRole('admin'), async (req, res) => {
  let user;
  try {
    const password = randomPassword();
    const built = buildArgs({ ...req.body, siteUserPassword: password });
    user = built.user;

    const { stdout } = await runClpctl(built.args);
    const safeArgs = built.args.map(a => a.startsWith('--siteUserPassword=') ? '--siteUserPassword=***' : a);
    audit.log(req.user, 'site.create', req.body.domainName, { type: req.body.type, siteUser: user });

    res.json({
      message: `Site ${req.body.domainName} created`,
      siteUser: user,
      siteUserPassword: password,
      note: 'This password is shown once and not stored — save it now. For Node.js/Python sites, deploy your app (via Files/Deploy) and start it with PM2 separately; clpctl only provisions the vhost.',
      command: safeArgs.join(' '),
      output: stdout,
    });
  } catch (err) {
    audit.log(req.user, 'site.create_failed', req.body?.domainName, { error: err.message });
    res.status(400).json({ error: 'Failed to create site', detail: err.message });
  }
});

// DELETE /api/vhosts/:domainName — admin only, permanently removes the site + its Linux user
router.delete('/:domainName', requireRole('admin'), async (req, res) => {
  try {
    const domainName = assertSafeArgValue('domainName', req.params.domainName);
    if (!isValidDomain(domainName)) return res.status(400).json({ error: 'Invalid domain name' });

    const { stdout } = await runClpctl(['site:delete', `--domainName=${domainName}`]);
    audit.log(req.user, 'site.delete', domainName);
    res.json({ message: `Site ${domainName} deleted`, output: stdout });
  } catch (err) {
    audit.log(req.user, 'site.delete_failed', req.params.domainName, { error: err.message });
    res.status(400).json({ error: 'Failed to delete site', detail: err.message });
  }
});

// POST /api/vhosts/ssl — admin only, issues a Let's Encrypt certificate
router.post('/ssl', requireRole('admin'), async (req, res) => {
  try {
    const domainName = assertSafeArgValue('domainName', req.body.domainName);
    if (!isValidDomain(domainName)) return res.status(400).json({ error: 'Invalid domain name' });

    const args = ['lets-encrypt:install:certificate', `--domainName=${domainName}`];
    if (req.body.subjectAlternativeName) {
      const san = assertSafeArgValue('subjectAlternativeName', req.body.subjectAlternativeName);
      args.push(`--subjectAlternativeName=${san}`);
    }

    const { stdout } = await runClpctl(args);
    audit.log(req.user, 'site.ssl_install', domainName);
    res.json({ message: `Certificate installed for ${domainName}`, output: stdout });
  } catch (err) {
    audit.log(req.user, 'site.ssl_install_failed', req.body?.domainName, { error: err.message });
    res.status(400).json({ error: 'Failed to install certificate', detail: err.message });
  }
});

module.exports = router;
